### ISSUE TITLE
Theme doesn't appear under `obconf`

### ISSUE THREAD

**Issue by ghost** [catppuccin/openbox#1]
- Installed `lxappearance`, `obconf`, `lxappearance-obconf`
- Cloned Catppuccin Openbox repository locally
- Copied `Catppuccin-Mocha` to `/usr/share/themes`
- Opened `obconf`

I can't seem to create a theme archive, either

**Comment by ghost** [comment]
It seems a little fiddling with Openbox solved the issue. Maybe a restart did it?

**Comment by prateektade** [comment]
In my experience, one need not restart Openbox after installing a theme for it to become visible in `obconf`.

We have plans to add theme archives for all flavors to make it much easier to install, I'll try to get it done.
